services:
  - type: web
    name: controle-financeiro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && mkdir -p data
    startCommand: python web_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
